### ISSUE TITLE
Installation succeeds, but no "forge"

### ISSUE THREAD

**Issue by hobart151** [aboutell/TheThickeningRoom#1]
Before doing anything, I found my version (which I had called 'Version latest 1.15.2' since that is what is was naming itself.  

10)Run installer.bat
Did this and I see the files in the Users/>user</AppData/Roaming/.minecraft/mods/Fabric directory (which appears to have been created today).

11)Launch your Minecraft Launcher.

12)Select Installations with the name you created in step 4...should be labelled with version 1.15.2 and delete it. DO NOT DELETE the version titled forge 1.15.2-forge-31.1.0
I found my "saved" version (which I had called 'Version latest 1.15.2' since that is what is was naming itself.  I deleted it.  There was no version named 'forge 1.15.2-forge-31.1.0', so I didn't delete it. lol.

13)Click on the Play Tab

14)Select the installation forge 1.15.2-forge-31.1.0, click Play.
No version

**Comment by hobart151** [comment]
Forgot to do the forge.jar expansion in your last note.

**Comment by aboutell** [comment]
Cool - yeah - I think the installer got messed up and "forgot" to run the Forge.jar installer!!
Glad it worked!!
