### ISSUE TITLE
Cannot connect to server: Do the needful

### ISSUE THREAD

**Issue by hobart151** [aboutell/TheThickeningRoom#6]
Priority 1 / customer down. Please make this your highest priority.
![Untitled](https://user-images.githubusercontent.com/63978256/92413186-ef09da00-f11c-11ea-83be-0ba3520ee9a4.jpg)

**Comment by hobart151** [comment]
Any ideas?

**Comment by aboutell** [comment]
Likely because this server is no longer online.  It was taken down in the fall of 2020 and replaced with a newly hosted server.  Please reach out to me on SLACK to get the IP address if you don't have it.
